package magic

const (
	//审批驳回
	CONTRACT_STATUS_REJECT = -1
	//审批中
	CONTRACT_STATUS_ING = 1
	//未完成
	CONTRACT_STATUS_UNFINISHED = 2
	//已完成
	CONTARCT_STATUS_FINISH = 3

	//生产中
	CONTATCT_PRODUCTION_STATUS_ING = 1
	//生产完成
	CONTATCT_PRODUCTION_STATUS_FINISH = 2

	//回款中
	CONTATCT_COLLECTION_STATUS_ING = 1
	//回款完成
	CONTATCT_COLLECTION_STATUS_FINISH = 2

	//待设计
	TASK_STATUS_NOT_DESIGN = 1
	//待采购
	TASK_STATUS_NOT_PURCHASE = 2
	//待入/出库
	TASK_STATUS_NOT_STORAGE = 3
	//待装配（非标设计流程独占）
	TASK_STATUS_NOT_ASSEMBLY = 4
	//待发货
	TASK_STATUS_NOT_SHIPMENT = 5
	//已发货
	TASK_STATUS_SHIPMENT = 6

	//标准/第三方有库存
	TASK_TYPE_1 = 1
	//标准/第三方无库存
	TASK_TYPE_2 = 2
	//非标准定制
	TASK_TYPE_3 = 3
)
