package magic

const (
	//审批驳回
	CONTRACT_STATUS_REJECT = -1
	//审批中
	CONTRACT_STATUS_ING = 1
	//未完成
	CONTRACT_STATUS_UNFINISHED = 2
	//已完成
	CONTARCT_STATUS_FINISH = 3

	//生产中
	CONTATCT_PRODUCTION_STATUS_ING = 1
	//生产完成
	CONTATCT_PRODUCTION_STATUS_FINISH = 2

	//回款中
	CONTATCT_COLLECTION_STATUS_ING = 1
	//回款完成
	CONTATCT_COLLECTION_STATUS_FINISH = 2

	//待设计
	TASK_STATUS_NOT_DESIGN = 1
	//待采购
	TASK_STATUS_NOT_PURCHASE = 2
	//待入库
	TASK_STATUS_NOT_STORAGE = 3
	//待发货
	TASK_STATUS_NOT_SHIPMENT = 4
	//待确认
	TASK_STATUS_NOT_CONFIRM = 5
	//完成
	TASK_STATUS_FINISH = 6
)
